# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"kitty" = "ï„ "

"firefox" = "ğŸŒ"
"chromium" = "ğŸŒ"

"nemo" = "ï¼"

"code" = "ï„¡"
"jetbrains-clion" = "ï„¡"
"jetbrains-toolbox" = "ï„¡"
"jetbrains-client" = "ï„¡"


"discord" = "ï’"
"telegramdesktop" = "ï‰º"
"thunderbird" = "ïƒ "

"tlp-ui" = "î•›"

"pavucontrol" = "ï€¨Q"
"blueberry.py" = "ïŠ”"

"bssh" = "ï‡«"
"bvnc" = "ï‡«"
"nm-connection-editor" = "ï‡«"

"xreader" = "ï…›"
"imv" = "ï‡…"
"zathura" = "ï‡"

"inkscape" = "ï‡¼"

"steam" = "ï¶"

"vorta" = ""
"dockeye" = ""



[other]
fallback_icon = "ï„‘"
deduplicate_icons = true
